apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env  : prod
    owner: DenisAstahov
spec:
  selector:
    project: {{ .Release.Name }}    
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : TCP
      port      : 8080  
      targetPort: 8080
  type: NodePort